<?php

namespace Buho\MylinksBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    
    public function getCommentsForLink($linkId, $approved=true)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.link = :link_id')
                   ->addOrderBy('c.created')
                   ->setParameter('link_id', $linkId);
        
        if (false === is_null($approved)) {
            $qb->andWhere('c.approved = :approved')
               ->setParameter('approved', $approved);
        }
        
        return $qb->getQuery()
                  ->getResult();
    }
}
