buho_mylinks_home:
    pattern:  /
    defaults: { _controller: BuhoMylinksBundle:Page:index }
    requirements:
        _method:  GET
    
buho_mylinks_about:
    pattern:  /about
    defaults: { _controller: BuhoMylinksBundle:Page:about }
    requirements:
        _method:  GET
    
buho_mylinks_contact:
    pattern:  /contact
    defaults: { _controller: BuhoMylinksBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
buho_mylinks_link_show:
    pattern:  /{id}
    defaults: { _controller: BuhoMylinksBundle:Link:show }
    requirements:
        _method:  GET
        id: \d+

buho_mylinks_link_new:
    pattern:  /link/new
    defaults: { _controller: BuhoMylinksBundle:Link:new }
    requirements:
        _method:  GET
        blog_id: \d+

buho_mylinks_link_create:
    pattern:  /link/{user_id}
    defaults: { _controller: BuhoMylinksBundle:Link:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
buho_mylinks_comment_create:
    pattern:  /comment/{link_id}
    defaults: { _controller: BuhoMylinksBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
